### PR TITLE
Candidate changes to help with missing HSI fragments at the start of …

### PR DESCRIPTION
**Pull request by bieryAtFnal**
…a run; the proposed fix is to allow the start of the readout window to be earlier than the oldest data in the buffer if the send_partial_fragment_if_available flag is set to true.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
These changes have companion changes in the daqconf repo.  Those changes are also on a branch called kbiery/AllowMissingDataAtStartOfRequestWindow.

Another alternative to these candidate changes would be to modify the original logic to allow missing data at the start of the window independent of the send_partial_fragment_if_not_yet/send_partial_fragment_if_available flag.  I'm not sure if that would be a bad choice for FELIX/WIB data, though.

**Comment by bieryAtFnal** [comment]
I should have mentioned that, with these changes, the lbrulibs/integtest/test_pacman-raw.py and dfmodules/integtest/minimal_system_quick_test.py tests no longer show warning messages about an empty HSI fragment.

**Comment by bieryAtFnal** [comment]
I've also made some changes to suppress warning messages from DefaultRequestHandlerModel when a 'show-warning' flag is set to false and configured it to false for HSI apps, to quiet a couple more cases in which the HSIDataLinkHandler generates empty fragments with SWTPG enabled.

**Comment by strilov** [comment]
Logic changes make sense to me, and my tests were successful.

**Pull request merged**
